ALTER TABLE City
ADD PRIMARY KEY (id);

ALTER TABLE Cafe
ADD FOREIGN KEY (city_id) REFERENCES City(id);

ALTER TABLE Cafe
ADD PRIMARY KEY (id);

ALTER TABLE Address
ADD FOREIGN KEY (cafe_id) REFERENCES Cafe(id);

ALTER TABLE Address
ADD FOREIGN KEY (city_id) REFERENCES City(id);

ALTER TABLE Phone
ADD PRIMARY KEY (id);

ALTER TABLE Phone
ADD FOREIGN KEY (id) REFERENCES Cafe(id);

ALTER TABLE Rates
ADD PRIMARY KEY (id);

ALTER TABLE Rates
ADD FOREIGN KEY (id) REFERENCES Cafe(id);

ALTER TABLE Features
ADD PRIMARY KEY (id);


ALTER TABLE Features_Cafe
ADD PRIMARY KEY (id);

ALTER TABLE Features_Cafe
ADD FOREIGN KEY (cafe_id) REFERENCES Cafe(id);

ALTER TABLE Features_Cafe
ADD FOREIGN KEY (id) REFERENCES Features(id);
